import type { Ward } from "@/features/patient/types/patient";

export const MOCK_WARDS: Ward[] = [
  {
    id: "71",
    name: "🛠️ 71병동 (일반내과)",
    rooms: [
      {
        id: "7101",
        name: "7101호",
        capacity: 6,
        patients: [
          {
            id: "p1",
            name: "김가민",
            age: 25,
            gender: "F",
            birthday: "1999.05.20",
            assignedNurse: "김영희",
            unconfirmedCount: 0,
          },
          {
            id: "p2",
            name: "이철수",
            age: 42,
            gender: "M",
            birthday: "1982.11.03",
            assignedNurse: "이수진",
            unconfirmedCount: 1,
          },
          {
            id: "p3",
            name: "박영희",
            age: 68,
            gender: "F",
            birthday: "1956.07.15",
            assignedNurse: "김영희",
            unconfirmedCount: 0,
          },
          {
            id: "p4",
            name: "최민호",
            age: 31,
            gender: "M",
            birthday: "1993.02.28",
            assignedNurse: "김영희",
            unconfirmedCount: 0,
          },
          {
            id: "p5",
            name: "정수연",
            age: 54,
            gender: "F",
            birthday: "1970.09.12",
            assignedNurse: "이수진",
            unconfirmedCount: 0,
          },
          {
            id: "p6",
            name: "강태우",
            age: 47,
            gender: "M",
            birthday: "1977.04.05",
            assignedNurse: "박민지",
            unconfirmedCount: 0,
          },
        ],
      },
      {
        id: "7102",
        name: "7102호",
        capacity: 6,
        patients: [
          {
            id: "p11",
            name: "한지민",
            age: 29,
            gender: "F",
            birthday: "1995.12.25",
            assignedNurse: "김영희",
            unconfirmedCount: 0,
          },
          {
            id: "p12",
            name: "윤도현",
            age: 52,
            gender: "M",
            birthday: "1972.03.14",
            assignedNurse: "최지원",
            unconfirmedCount: 2,
          },
        ],
      },
    ],
  },
  {
    id: "72",
    name: "🛠️ 72병동 (소화기내과)",
    rooms: [],
  },
  {
    id: "icu",
    name: "🛠️ ICU (중환자실)",
    rooms: [],
  },
  {
    id: "er",
    name: "🛠️ ER (응급실)",
    rooms: [],
  },
];
