spring.application.name=happynurse

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/happynurse
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# JWT
jwt.secret=dGhpcyBpcyBhIHNhbXBsZSBzZWNyZXQga2V5IGZvciBkZXY=
jwt.access-token-expiration-ms=1800000
jwt.cookie-name=ACCESS_TOKEN
jwt.cookie-secure=false
jwt.cookie-same-site=Lax